# Element Wise Operations in NumPy


## Overview

As we know for Deep Learning most of the data is represented as tensors and so we need to perform element wise operations on these tensors.

Let us compare how we can achive this by using python as well as NumPy

Let us consider we have a list of numbers

In [4]:
a = [1,2,3,4,5]

Let us say that we need to add *5* to every element,
the pythonic way to do so would be

In [5]:
for i in range(len(a)):
    a[i] += 5
print(a)

[6, 7, 8, 9, 10]


Now this is pure python and as we have said this could be very slow so lets see what is the NumPy way to do this.

In [7]:
import numpy as np

In [8]:
values = np.array([1,2,3,4,5])
values = values + 5
print(values)

[ 6  7  8  9 10]


This is one way of doing it what we could also do is 

In [9]:
values += 5
print(values)

[11 12 13 14 15]


Normally we would already have an ndarray values and this is how we would do element wise operation in NumPy

NumPy had functions for performing operations like multiplication.

In [13]:
x = np.multiply([1,2,3,4],5)
print(x)


[ 5 10 15 20]


Now, Let us take a matrix m

In [14]:
m = [[1,2,3],[4,5,6],[7,8,9]]
print(m)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


If we want to reset the values of this matrix we can do something like

In [15]:
m *= 0
print(m)

[]


## Element wise matrix operations

Let us consider two matrix a and b 

In [17]:
a = np.array([1,2,3])
print(a)
b = np.array([4,5,6])
print(b)
a + b

[1 2 3]
[4 5 6]


array([5, 7, 9])

*Note* We are able to perform these operation only because the shapes of these tensors are same

In [18]:
c = np.array([1,2])
a + c

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

Here we get an error because the shape of the two tensors are not same