# Matrix Multiplication Using NumPY

Element wise multiplication is fairly simple

In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print()
b = a*0.5
print(b)
print()
c = a*b
print(c)

[[1 2 3]
 [4 5 6]]

[[0.5 1.  1.5]
 [2.  2.5 3. ]]

[[ 0.5  2.   4.5]
 [ 8.  12.5 18. ]]


The c = a * b can also be performed as

In [4]:
c = np.multiply(a,b)
c

array([[ 0.5,  2. ,  4.5],
       [ 8. , 12.5, 18. ]])