# Matrix Multiplication Using NumPy

Element wise multiplication is fairly simple

In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print()
b = a*0.5
print(b)
print()
c = a*b
print(c)

[[1 2 3]
 [4 5 6]]

[[0.5 1.  1.5]
 [2.  2.5 3. ]]

[[ 0.5  2.   4.5]
 [ 8.  12.5 18. ]]


The c = a * b can also be performed as

In [5]:
c = np.multiply(a,b)
c

array([[ 0.5,  2. ,  4.5],
       [ 8. , 12.5, 18. ]])

## Matrix Multiplication

In order to do matrix multiplications the shapes of the matrix need to be compatable

In [6]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a.shape)
print(b.shape)

(2, 4)
(4, 3)


Since the number of colume of a is equal to the number of row of b we can to matrix multiplication by using matmul function of NumPy

In [9]:
c = np.matmul(a,b)
print(c.shape)
print(c)

(2, 3)
[[ 70  80  90]
 [158 184 210]]


If we have to do dot product we can use the dot function

In [11]:
a = np.array([[1,2],[3,4]])
print(a)
print()
b = np.dot(a,a)
print(b)
print()
print(a.dot(a))
print()
c = np.matmul(a,a)
print(c)

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[ 7 10]
 [15 22]]

[[ 7 10]
 [15 22]]
