# Transpose

Sometimes we need to use the transpose of a matrix to do certain operations.
In NumPy we can achieve this by just using T


In [2]:
import numpy as np

In [4]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print()
print(a.T)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


## Usecase

Lets say we have two matrices inputs and weights

In [5]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

If we check the shape of these matrices 

In [9]:
print(inputs.shape)
print(weights.shape)

(1, 4)
(3, 4)


We cannot clearly do matrix multiplication here if we try to do so we would get an error

In [10]:
print(np.matmul(inputs,weights))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

But instead if we take the transpose and multiply we could achieve this

In [11]:
print(np.matmul(inputs,weights.T))

[[-0.01299  0.00664  0.13494]]


Even the shapes would checkout

In [12]:
print(inputs.shape)
print(weights.T.shape)

(1, 4)
(4, 3)
